{{- define "multr.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: multr
data:
  cpu: |
    config for cpu nodes
  gpu: |
    config for gpu nodes
{{- end }}

{{- if .Values.deploy_configmap }}
{{- include "multr.configmap" . }}
{{- end }}
